Personality_Options:
  name: Crowing
  tone: ""
  language: ""
  
Folders_Config:
  exemples_nest: ""
  exemples_go: ""
  main_folder: ""
  log_folder: ""

Configs_Global:
  choices:
    - Eso Builder
    - Projeto Automatico
    - Midia Organizador
    - Opções
    - Pagamentos

Payment_Config:
  Total_Card: 0
  Total_For_Pay: 0
  slips:
    - Name: ""
      Value: 0
